stages:
  - test

secret_detection:
  stage: test
  image: registry.gitlab.com/gitlab-org/security-products/analyzers/secrets
  script:
    - /analyzer run
    - if [ ! -f gl-secret-detection-report.json ]; then echo "{}" > gl-secret-detection-report.json; fi
  artifacts:
    paths:
      - gl-secret-detection-report.json
    expire_in: 1 week  # Optional, adjust or remove based on your needs
    reports:
      secret_detection: gl-secret-detection-report.json

security_scan:
  stage: test
  image: node:latest
  script:
    - ls -la  # List directory contents to check for .js files
    - npm install jshint  # Install JSHint
    - npx jshint *.js > jshint_report.txt || true  # Run JSHint and ignore errors
  artifacts:
    when: always
    paths:
      - jshint_report.txt  # Collect the JSHint report as an artifact
  allow_failure: true
