# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jCWIbIuCafg-d6UPjDBYjnbxgdt4-hUH
"""

import requests
import openai
import smtplib
from email.mime.text import MIMEText
from datetime import datetime, timedelta

# === 🔐 CONFIGURATION ===
NEWS_API_KEY = ""
OPENAI_API_KEY = ""
GMAIL_ADDRESS = "mcgarry72@gmail.com"
GMAIL_APP_PASSWORD = ""  # from https://myaccount.google.com/apppasswords
TO_EMAIL = "mcgarrym@vcu.edu"  # Can be the same or different

# === 📅 GET YESTERDAY'S DATE ===
yesterday_date = datetime.now() - timedelta(days=1)
yesterday_str = yesterday_date.strftime("%Y-%m-%d")
subject_line = f"Daily News Summary – AI & Higher Education ({yesterday_str})"

# === 🔎 BUILD NEWSAPI QUERY ===
query = '("AI" OR "Artificial Intelligence") OR ("higher education" OR "university" OR "college")'
url = (
    "https://newsapi.org/v2/everything?"
    f"q={query}&"
    f"from={yesterday_str}&to={yesterday_str}&"
    "language=en&"
    "sortBy=publishedAt&"
    "searchIn=title&"
    f"apiKey={NEWS_API_KEY}"
)

# === 🤖 SET UP OPENAI CLIENT ===
client = openai.OpenAI(api_key=OPENAI_API_KEY)

# === 📡 FETCH ARTICLES ===
def fetch_news_articles():
    response = requests.get(url)
    data = response.json()
    if data["status"] != "ok":
        raise Exception("NewsAPI error: " + data.get("message", "Unknown error"))
    return data["articles"][:5]  # limit to 5

# === 🧠 SUMMARIZE WITH OPENAI ===
def summarize_text(text):
    response = client.chat.completions.create(
        model="gpt-4",
        messages=[
            {"role": "system", "content": "Summarize this news article in 1–2 sentences."},
            {"role": "user", "content": text}
        ]
    )
    return response.choices[0].message.content.strip()

# === 📨 FORMAT SUMMARY FOR EMAIL ===
def build_email_summary(articles):
    lines = [subject_line, "", f"📅 Date: {yesterday_str}", ""]
    for i, article in enumerate(articles, start=1):
        title = article["title"]
        link = article["url"]
        description = article.get("description", "")
        summary = summarize_text(title + "\n\n" + description)
        lines.extend([
            f"📰 [{i}] {title}",
            f"🔗 {link}",
            f"🧠 Summary: {summary}",
            "-" * 80
        ])
    return "\n".join(lines)

# === ✉️ SEND THE EMAIL ===
def send_email(subject, body):
    msg = MIMEText(body, "plain")
    msg["Subject"] = subject
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = TO_EMAIL

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(GMAIL_ADDRESS, GMAIL_APP_PASSWORD)
        server.send_message(msg)

    print("✅ Email sent.")

# === 🚀 MAIN ===
def main():
    print(f"⏳ Fetching articles for {yesterday_str}...")
    articles = fetch_news_articles()
    if not articles:
        print("⚠️ No articles found for yesterday.")
        return
    email_body = build_email_summary(articles)
    send_email(subject_line, email_body)

if __name__ == "__main__":
    main()
